import { Link } from 'react-router-dom';

export default function Privacy() {
  return (
    <div className="min-h-screen bg-[#F9F7F2] font-sans">
      <nav className="bg-white border-b border-stone-200 sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="font-bold text-stone-900 hover:text-[#76B900] transition-colors">← CivicPath</Link>
          <div className="flex gap-4 text-sm text-stone-500">
            <Link to="/terms" className="hover:text-stone-700">Terms</Link>
            <Link to="/pricing" className="hover:text-stone-700">Pricing</Link>
          </div>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-[900] text-stone-900 mb-2">Privacy Policy</h1>
        <p className="text-stone-400 text-sm mb-10">Last updated: March 23, 2026</p>
        <div className="prose prose-stone max-w-none space-y-8 text-stone-600 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">1. Sovereign Data Infrastructure</h2>
            <p>CivicPath is built on sovereign architecture. Your organizational data, grant applications, proposals, and profile information are hardware-isolated and never shared with third-party commercial cloud services. All processing occurs within our secure, isolated environment.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">2. Information We Collect</h2>
            <p>We collect information you provide directly: organization name, mission, location, focus areas, background information, and contact details. We also collect authentication information via Firebase (email/password or Google OAuth) and usage data to improve our service.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">3. How We Use Your Information</h2>
            <p>Your profile data is used exclusively to match you with relevant grants using Gemini AI. We do not sell, rent, or share your information with third parties for marketing purposes. Grant proposals generated by our AI agents are yours — we do not retain ownership.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">4. Data Security</h2>
            <p>We implement industry-standard security measures including encrypted data transmission (TLS), Firebase Authentication for secure login, and isolated infrastructure. Your API keys and sensitive credentials are stored as environment variables and never exposed client-side in production.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">5. Third-Party Services</h2>
            <p>We use Firebase (Google) for authentication, Gemini AI (Google) for proposal generation, and Vercel for hosting. Each of these services has their own privacy policies. We use your Gemini API key solely to generate grant proposals on your behalf.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">6. Your Rights</h2>
            <p>You have the right to access, correct, or delete your personal data at any time. To request data deletion, contact us at privacy@civicpath.ai. You may also delete your account through the Settings page.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">7. Contact</h2>
            <p>For privacy questions: <a href="mailto:privacy@civicpath.ai" className="text-[#76B900] hover:underline">privacy@civicpath.ai</a><br />
            CivicPath is a product of HelloAgentic, built in Florida.</p>
          </section>
        </div>
      </div>
      <footer className="border-t border-stone-200 py-8 text-center text-sm text-stone-400">
        <Link to="/" className="hover:text-stone-700 mr-4">Home</Link>
        <Link to="/terms" className="hover:text-stone-700 mr-4">Terms</Link>
        <Link to="/pricing" className="hover:text-stone-700">Pricing</Link>
      </footer>
    </div>
  );
}
