import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#F9F7F2] font-sans">
      <nav className="bg-white border-b border-stone-200 sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="font-bold text-stone-900 hover:text-[#76B900] transition-colors">← CivicPath</Link>
          <div className="flex gap-4 text-sm text-stone-500">
            <Link to="/privacy" className="hover:text-stone-700">Privacy</Link>
            <Link to="/pricing" className="hover:text-stone-700">Pricing</Link>
          </div>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-[900] text-stone-900 mb-2">Terms of Service</h1>
        <p className="text-stone-400 text-sm mb-10">Last updated: March 23, 2026</p>
        <div className="space-y-8 text-stone-600 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using CivicPath, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform. CivicPath is operated by HelloAgentic.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">2. Description of Service</h2>
            <p>CivicPath is an AI-powered grant marketplace that connects grant seekers with grant funders. We use Gemini AI to match organizations to grants, generate proposals, and facilitate the application process. The platform is provided as a tool to assist — all final decisions rest with the user.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">3. User Accounts</h2>
            <p>You are responsible for maintaining the security of your account. You must provide accurate information when creating an account. We reserve the right to terminate accounts that violate these terms or are used for fraudulent purposes.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">4. AI-Generated Content</h2>
            <p>Proposals and content generated by our AI agents are provided as drafts to assist your grant application process. You are solely responsible for reviewing, verifying, and submitting any applications. CivicPath does not guarantee funding outcomes.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">5. Prohibited Uses</h2>
            <p>You may not use CivicPath to submit fraudulent grant applications, misrepresent your organization, spam grant funders, or violate any applicable laws. Violations will result in immediate account termination.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">6. Intellectual Property</h2>
            <p>Content you create using CivicPath (proposals, profiles) remains your property. The CivicPath platform, branding, and AI systems are owned by HelloAgentic and protected by applicable intellectual property laws.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">7. Limitation of Liability</h2>
            <p>CivicPath is provided "as is" without warranty of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform or any funding decisions made by third parties.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-stone-900 mb-3">8. Contact</h2>
            <p>For questions about these terms: <a href="mailto:legal@civicpath.ai" className="text-[#76B900] hover:underline">legal@civicpath.ai</a><br />
            HelloAgentic · Built in Florida · © 2026</p>
          </section>
        </div>
      </div>
      <footer className="border-t border-stone-200 py-8 text-center text-sm text-stone-400">
        <Link to="/" className="hover:text-stone-700 mr-4">Home</Link>
        <Link to="/privacy" className="hover:text-stone-700 mr-4">Privacy</Link>
        <Link to="/pricing" className="hover:text-stone-700">Pricing</Link>
      </footer>
    </div>
  );
}
